### PR TITLE
Boilerplate bootstrap 1 bb13099762b9a98c72498c2d6e3d7a3672e73be2

### PR DESCRIPTION
**Pull request by shibumi**
This is an automated generated PR by the openshift/boilerplate. It's goal is to apply the boilerplate layout to our project for the APP-SRE onboarding

### CODE REVIEW

**Comment by georgettica** [comment]
Description?

**Comment by georgettica** [comment]
If this was created by the boilerplate, maybe the commit it creates can have a description

**Comment by shibumi** [comment]
@georgettica  I have attached a description to this PR.. it's autogenerated by `openshift/boilerplate`

**Comment by georgettica** [comment]
Fix the validate and then I can lgtm

**Comment by georgettica** [comment]
looks great!
/lgtm

**Pull request merged**
