### PR TITLE
chore: add more approvers

### PR DESCRIPTION
**Pull request by shibumi**
Add more approvers for faster development cycles

### CODE REVIEW

**Comment by shibumi** [comment]
Interesting.. so the auto merge does not work yet. I would have assumed that giving the app-sre-bot write access to this repository would allow auto-merging :thinking:

**Comment by georgettica** [comment]
So I would say it might be because of our prow config is missing something

**Comment by shibumi** [comment]
@georgettica  yes, you are correct. I assumed that the app-sre-bot would be responsible for this, but turns out it's the prow Ci bot

**Comment by shibumi** [comment]
@georgettica  we can copy this behavior from here: https://github.com/openshift/release/tree/master/ci-operator/config/openshift/aws-account-operator

**Pull request merged**
