### PR TITLE
chore: bump Go to 1.18

### PR DESCRIPTION
**Pull request by shibumi**
I don't know if this would make sense, because openshift/boilerplate is still on Go 1.17, but I bumped CAD on Go 1.18 and it builds.

Would it make sense to bump to Go 1.18 or do we wait?

### CODE REVIEW

**Comment by georgettica** [comment]
I want to go 1.18, but we _should_ wait for the whole org

basically did something similar in RMO (moved to latest operator-sdk) and not it's like a sore thumb

not opposed, but not sure if to say yes to this

**Comment by georgettica** [comment]
/retest
this error is not something in the code I think

**Comment by shibumi** [comment]
@georgettica it's a timeout in the linter

**Comment by georgettica** [comment]
let's give a huge timeout  `--timeout=5m` and add `--verbose`  to see where it fails

**Comment by shibumi** [comment]
@georgettica  lol.. my local golangci-lint fails:
```
❯ golangci-lint run --help
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
        github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
```

**Comment by georgettica** [comment]
see - https://github.com/go-critic/go-critic/issues/1193

**Comment by georgettica** [comment]
so let's stay on go1.17, as all the linters work there :)
once they are mature enough we'll migrate?

**Comment by shibumi** [comment]
> so let's stay on go1.17, as all the linters work there :)
> once they are mature enough we'll migrate?

Sounds good. Do we leave this PR open or do we close it? I think it would make sense to close it, but document our problems somewhere... we might run into the same issues in a year when we try to upgrade to Go 1.18

**Comment by shibumi** [comment]
This is from now on tracked in: OSD-10639

**Pull request closed without merging**
