### PR TITLE
chore(lint): add misspell linter

### PR DESCRIPTION
**Pull request by georgettica**
this is super cool and it finds common misspells

### CODE REVIEW

**Review by shibumi — APPROVED** [review]

**Comment by georgettica** [comment]
let's see if I can approve my own PR
/apprve

**Comment by georgettica** [comment]
We should decide if we should merge them or even use this CLI too #32

**Comment by shibumi** [comment]
I am fine with using a tool for spell checking.. as far as it is opt-in and a human checks the diff first.

**Pull request merged**
